export const DEFAULT_SOCKET_ORDER_NOTIFICATION_URL = 'http://192.168.245.61:4001'
export const SOCKET_ORDER_NOTIFICATION_URL =
  process.env.REACT_APP_ORDER_NOTIFICATION_SOCKET_URL || DEFAULT_SOCKET_ORDER_NOTIFICATION_URL
export const ORDER_NOTIFICATION_EVENT = 'order_update'
export const NOTIFICATION_DROPDOWN_LIMIT = 20

export const ORDER_NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  WAITING_PAYMENT: 'WAITING_PAYMENT',
  PAID: 'PAID',
  SHIPPING: 'SHIPPING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  CUSTOMER_CANCELLED: 'CUSTOMER_CANCELLED',
  UNKNOWN: 'UNKNOWN',
}

export const ORDER_NOTIFICATION_STATUS_TEXT_MAP = {
  'Đang chờ xử lý': ORDER_NOTIFICATION_STATUS.PENDING,
  'Chờ thanh toán': ORDER_NOTIFICATION_STATUS.WAITING_PAYMENT,
  'Đã thanh toán': ORDER_NOTIFICATION_STATUS.PAID,
  'Đang giao hàng': ORDER_NOTIFICATION_STATUS.SHIPPING,
  'Đã hoàn tất': ORDER_NOTIFICATION_STATUS.COMPLETED,
  'Đã hủy bỏ': ORDER_NOTIFICATION_STATUS.CANCELLED,
  'Khách hàng hủy bỏ': ORDER_NOTIFICATION_STATUS.CUSTOMER_CANCELLED,
}
